#
# /etc/doas.conf
#

# void
permit persist :wheel as root

permit nopass :adm as root cmd /bin/dmesg
permit nopass :adm as root cmd /bin/vkpurge args list
permit nopass :adm as root cmd /bin/vkpurge args rm all
permit nopass :adm as root cmd /bin/xbps-install args -Syu xbps
permit nopass :adm as root cmd /bin/xbps-install args -yu
permit nopass :adm as root cmd /bin/xbps-remove args -RyoO
permit nopass :adm as root cmd /bin/zzz args -H
permit nopass :adm as root cmd /bin/zzz args -Z
permit nopass :adm as root cmd /bin/ZZZ args -H
permit nopass :adm as root cmd /bin/ZZZ args -Z

