#!/bin/sh

#
# ~/.ssh/add_ssh_keys
#

TIMEOUT="4h"

add_ssh_keys() {
	grep Identity "$HOME"/.ssh/config | awk '{print $2}' | while read -r key
	do
		key_fn="$HOME/.ssh/$(basename "$key")"
		if [ -s "$key_fn" ]
		then
			ssh-add "$key_fn"
		fi
	done
}

start_ssh_agent() {
	rm -f "$SSH_AUTH_SOCK"
	ssh-agent -t "$TIMEOUT" -a "$SSH_AUTH_SOCK" > /dev/null 2>&1
}

if ! pgrep ssh-agent >/dev/null
then
	start_ssh_agent
fi

if ! ssh-add -l >/dev/null 2>&1
then
	add_ssh_keys
fi
